name: 'the_tuva_project'
version: '0.3.13'
config-version: 2
require-dbt-version: ">=1.3.0"

profile: default

vars:

    ## CCSR data mart vars
    # These vars enable the wide tables - disabling will exclude wide tables from dbt runs
    wide_condition_enabled: True
    wide_procedure_enabled: True

    # Set to "ip" for inpatient data or "op" for outpatient data (More info in the README)
    record_type: "ip"

    # CCSR Version numbers from HCUP
    dxccsr_version: "'2023.1'"
    prccsr_version: "'2023.1'"


    ## CMS HCC data mart vars
    # The payment_year variable has a default of the current year
    cms_hcc_payment_year: 2023

    # DO NOT CHANGE - Future logic to be added for selecting different HCC model versions
    cms_hcc_model_version: CMS-HCC-V24


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

seeds:
  the_tuva_project:
    terminology:
      terminology__calendar:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology','calendar.csv') }}"
      terminology__icd_10_pcs:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology','icd_10_pcs.csv') }}"
      terminology__icd_10_cm:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology','icd_10_cm.csv') }}"
      terminology__other_provider_taxonomy:
        +post-hook: "{{ load_seed('tuva-public-resources/provider_data','other_provider_taxonomy.csv') }}"
      terminology__provider:
        +post-hook: "{{ load_seed('tuva-public-resources/provider_data','provider.csv') }}"
    value_sets:
      ccsr:
        ccsr__dxccsr_v2023_1_cleaned_map:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','dxccsr_v2023_1_cleaned_map.csv') }}"
        ccsr__prccsr_v2023_1_cleaned_map:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','prccsr_v2023_1_cleaned_map.csv') }}"
      readmissions:
        readmissions__icd_10_pcs_to_ccs:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','icd_10_pcs_to_ccs.csv') }}"
        readmissions__icd_10_cm_to_ccs:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','icd_10_cm_to_ccs.csv') }}"
