name: 'the_tuva_project'
version: '0.8.0'
config-version: 2
require-dbt-version: ">=1.3.0"


profile: default

vars:

    ## CCSR data mart vars
    # Set to "ip" for inpatient data or "op" for outpatient data (More info in the README)
    record_type: "ip"

    # CCSR Version numbers from HCUP
    dxccsr_version: "'2023.1'"
    prccsr_version: "'2023.1'"


    ## CMS HCC data mart vars
    # The payment_year variable has a default of the current year, this can be
    # changed by adding the numeric value of a year (ex: cms_hcc_payment_year: 2019)
    cms_hcc_payment_year: '{{ run_started_at.strftime("%Y") }}'


    ## Quality Measures period var
    # to run quality measueres for a period other than current year, add the below variable uncommented to your project
    # quality_measures_period_end: "2020-12-31"


    ## Tuva Last Run
    # The date and timestamp of the dbt run that will populate the tuva_last_run column in all models.
    # Default timezone is UTC
    tuva_last_run: '{{ run_started_at.astimezone(modules.pytz.timezone("UTC")) }}'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

seeds:
  the_tuva_project:
    terminology:
      terminology__admit_source:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','admit_source.csv',compression=true,null_marker=true) }}"
      terminology__admit_type:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','admit_type.csv',compression=true,null_marker=true) }}"
      terminology__ansi_fips_state:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','ansi_fips_state.csv',compression=true,null_marker=true) }}"
      terminology__apr_drg:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','apr_drg.csv',compression=true,null_marker=true) }}"
      terminology__bill_type:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','bill_type.csv',compression=true,null_marker=true) }}"
      terminology__calendar:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','calendar.csv',compression=true,null_marker=true) }}"
      terminology__claim_type:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','claim_type.csv',compression=true,null_marker=true) }}"
      terminology__code_type:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','code_type.csv',compression=true,null_marker=true) }}"
      terminology__discharge_disposition:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','discharge_disposition.csv',compression=true,null_marker=true) }}"
      terminology__encounter_type:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','encounter_type.csv',compression=true,null_marker=true) }}"
      terminology__ethnicity:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','ethnicity.csv',compression=true,null_marker=true) }}"
      terminology__fips_county:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','fips_county.csv',compression=true,null_marker=true) }}"
      terminology__gender:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','gender.csv',compression=true,null_marker=true) }}"
      terminology__hcpcs_level_2:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','hcpcs_level_2.csv',compression=true,null_marker=true) }}"
      terminology__icd_10_cm:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','icd_10_cm.csv',compression=true,null_marker=true) }}"
      terminology__icd_10_pcs:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','icd_10_pcs.csv',compression=true,null_marker=true) }}"
      terminology__icd_9_cm:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','icd_9_cm.csv',compression=true,null_marker=true) }}"
      terminology__icd_9_pcs:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','icd_9_pcs.csv',compression=true,null_marker=true) }}"
      terminology__loinc:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','loinc.csv',compression=true,null_marker=true) }}"
      terminology__loinc_deprecated_mapping:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','loinc_deprecated_mapping.csv',compression=true,null_marker=true) }}"
      terminology__mdc:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','mdc.csv',compression=true,null_marker=true) }}"
      terminology__medicare_dual_eligibility:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','medicare_dual_eligibility.csv',compression=true,null_marker=true) }}"
      terminology__medicare_orec:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','medicare_orec.csv',compression=true,null_marker=true) }}"
      terminology__medicare_status:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','medicare_status.csv',compression=true,null_marker=true) }}"
      terminology__ms_drg:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','ms_drg.csv',compression=true,null_marker=true) }}"
      terminology__ndc:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','ndc.csv',compression=true,null_marker=true) }}"
      terminology__other_provider_taxonomy:
        +post-hook: "{{ load_seed('tuva-public-resources/provider_data','other_provider_taxonomy.csv',compression=true,null_marker=true) }}"
      terminology__payer_type:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','payer_type.csv',compression=true,null_marker=true) }}"
      terminology__place_of_service:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','place_of_service.csv',compression=true,null_marker=true) }}"
      terminology__present_on_admission:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','present_on_admission.csv',compression=true,null_marker=true) }}"
      terminology__provider:
        +post-hook: "{{ load_seed('tuva-public-resources/provider_data','provider.csv',compression=true,null_marker=true) }}"
      terminology__race:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','race.csv',compression=true,null_marker=true) }}"
      terminology__revenue_center:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','revenue_center.csv',compression=true,null_marker=true) }}"
      terminology__rxnorm_to_atc:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','rxnorm_to_atc.csv',compression=true,null_marker=true) }}"
      terminology__snomed_ct:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','snomed_ct.csv',compression=true,null_marker=true) }}"
      terminology__snomed_ct_transitive_closures:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','snomed_ct_transitive_closures.csv',compression=true,null_marker=true) }}"
      terminology__snomed_icd_10_map:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','snomed_icd_10_map.csv',compression=true,null_marker=true) }}"
      terminology__ssa_fips_state:
        +post-hook: "{{ load_seed('tuva-public-resources/versioned_terminology','ssa_fips_state.csv',compression=true,null_marker=true) }}"

    value_sets:
      ccsr:
        ccsr__dxccsr_v2023_1_body_systems:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','dxccsr_v2023_1_body_systems.csv',compression=true,null_marker=true) }}"
        ccsr__dxccsr_v2023_1_cleaned_map:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','dxccsr_v2023_1_cleaned_map.csv',compression=true,null_marker=true) }}"
        ccsr__prccsr_v2023_1_cleaned_map:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','prccsr_v2023_1_cleaned_map.csv',compression=true,null_marker=true) }}"
      chronic_conditions:
        chronic_conditions__cms_chronic_conditions_hierarchy:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','cms_chronic_conditions_hierarchy.csv',compression=true,null_marker=true) }}"
        chronic_conditions__tuva_chronic_conditions_hierarchy:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','tuva_chronic_conditions_hierarchy.csv',compression=true,null_marker=true) }}"
      clinical_concept_library:
        clinical_concepts:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','clinical_concepts.csv',compression=true,null_marker=true) }}"
        coding_systems:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','coding_systems.csv',compression=true,null_marker=true) }}"
        value_set_members:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','value_set_members.csv',compression=true,null_marker=true) }}"
      cms_hcc:
        cms_hcc__adjustment_rates:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','adjustment_rates.csv',compression=true,null_marker=true) }}"
        cms_hcc__cpt_hcpcs:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','cpt_hcpcs.csv',compression=true,null_marker=true) }}"
        cms_hcc__demographic_factors:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','demographic_factors.csv',compression=true,null_marker=true) }}"
        cms_hcc__disabled_interaction_factors:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','disabled_interaction_factors.csv',compression=true,null_marker=true) }}"
        cms_hcc__disease_factors:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','disease_factors.csv',compression=true,null_marker=true) }}"
        cms_hcc__disease_interaction_factors:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','disease_interaction_factors.csv',compression=true,null_marker=true) }}"
        cms_hcc__enrollment_interaction_factors:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','enrollment_interaction_factors.csv',compression=true,null_marker=true) }}"
        cms_hcc__icd_10_cm_mappings:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','cms_hcc_icd_10_cm_mappings.csv',compression=true,null_marker=true) }}"
        cms_hcc__payment_hcc_count_factors:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','payment_hcc_count_factors.csv',compression=true,null_marker=true) }}"
      ed_classification:
        ed_classification__categories:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','categories.csv',compression=true,null_marker=true) }}"
        ed_classification__icd_10_cm_to_ccs:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','icd_10_cm_to_ccs.csv',compression=true,null_marker=true) }}"
        ed_classification__johnston_icd10:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','johnston_icd10',compression=true,null_marker=true) }}"
        ed_classification__johnston_icd9:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','johnston_icd9',compression=true,null_marker=true) }}"
      hcc_suspecting:
        hcc_suspecting__clinical_concepts:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','clinical_concepts.csv',compression=true,null_marker=true) }}"
        hcc_suspecting__hcc_descriptions:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','hcc_descriptions.csv',compression=true,null_marker=true) }}"
        hcc_suspecting__icd_10_cm_mappings:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','hcc_suspecting_icd_10_cm_mappings.csv',compression=true,null_marker=true) }}"
      quality_measures:
        quality_measures__concepts:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','concepts.csv',compression=true,null_marker=true) }}"
        quality_measures__measures:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','measures.csv',compression=true,null_marker=true) }}"
        quality_measures__value_sets:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','value_sets.csv',compression=true,null_marker=true) }}"
      readmissions:
        readmissions__acute_diagnosis_ccs:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','acute_diagnosis_ccs.csv',compression=true,null_marker=true) }}"
        readmissions__acute_diagnosis_icd_10_cm:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','acute_diagnosis_icd_10_cm.csv',compression=true,null_marker=true) }}"
        readmissions__always_planned_ccs_diagnosis_cateogry:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','always_planned_ccs_diagnosis_cateogry.csv',compression=true,null_marker=true) }}"
        readmissions__always_planned_ccs_procedure_cateogry:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','always_planned_ccs_procedure_cateogry.csv',compression=true,null_marker=true) }}"
        readmissions__exclusion_ccs_diagnosis_category:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','exclusion_ccs_diagnosis_category.csv',compression=true,null_marker=true) }}"
        readmissions__icd_10_cm_to_ccs:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','icd_10_cm_to_ccs.csv',compression=true,null_marker=true) }}"
        readmissions__icd_10_pcs_to_ccs:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','icd_10_pcs_to_ccs.csv',compression=true,null_marker=true) }}"
        readmissions__potentially_planned_ccs_procedure_category:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','potentially_planned_ccs_procedure_category.csv',compression=true,null_marker=true) }}"
        readmissions__potentially_planned_icd_10_pcs:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','potentially_planned_icd_10_pcs.csv',compression=true,null_marker=true) }}"
        readmissions__specialty_cohort:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','specialty_cohort.csv',compression=true,null_marker=true) }}"
        readmissions__surgery_gyncology_cohort:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','surgery_gyncology_cohort.csv',compression=true,null_marker=true) }}"
