name: 'the_tuva_project'
version: '0.3.10'
config-version: 2
require-dbt-version: ">=1.3.0"

profile: default

vars:

    ## These vars are specific to the CCSR data mart
    # These vars enable the wide tables - disabling will exclude wide tables from dbt runs
    wide_condition_enabled: True
    wide_procedure_enabled: True

    # Set to "ip" for inpatient data or "op" for outpatient data (More info in the README)
    record_type: "ip"

    # CCSR Version numbers from HCUP
    dxccsr_version: "'2023.1'"
    prccsr_version: "'2023.1'"

    ## These vars are specific to the CMS HCC data mart
    # The payment_year variable has a default of the current year
    # it can be changed here or during execution with
    # the syntax: dbt build --vars '{payment_year: 2022}'
    cms_hcc_payment_year: 2023

    # DO NOT CHANGE - Future logic to be added for selecting different HCC model versions
    cms_hcc_model_version: CMS-HCC-V24


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

seeds:
  the_tuva_project:
    terminology:
      terminology__provider:
        +post-hook: "{{ load_seed('tuva-public-resources/provider_data','provider.csv') }}"
      terminology__other_provider_taxonomy:
        +post-hook: "{{ load_seed('tuva-public-resources/provider_data','other_provider_taxonomy.csv') }}"
