name: 'tuva_dbt_core'
version: '0.2.0'
config-version: 2

# TODO can this go away?
profile: tuva_sandbox      # configuration required (your profile to connect dbt to your data warehouse)

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
    tuva_dbt_core:
        +tags:
            - tuva_dbt_core
