name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: 

vars:

  input_database: 
  input_schema: 

  ## All Tuva Data Marts
  tuva_marts_enabled: true
  
  ## Individual Tuva Data Marts
  # ccsr_enabled: true
  # cms_chronic_conditions_enabled: false
  # tuva_chronic_conditions_enabled: false
  # claims_date_profiling_enabled: false
  # core_enabled: true
  # data_profiling_enabled: false
  # encounter_grouper_enabled: true
  # member_months_enabled: false
  # pmpm_enabled: false
  # readmissions_enabled: false
  # service_category_grouper_enabled: true

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  integration_tests:
    +database: 
  the_tuva_project:
    +database: 

seeds:
  the_tuva_project:
    +database: 

