name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: default

vars:

#  input_database: tuva_project_demo
#  input_schema: tuva_synthetic

  ## All Data Marts
  tuva_marts_enabled: true

  # ## Input Layer
  # input_layer_enabled: false
  
  # ## Claims Data Marts
  # member_months_enabled: true
  # service_category_grouper_enabled: true
  # pmpm_enabled: true
  # encounter_grouper_enabled: false
  # data_profiling_enabled: false
  # claims_date_profiling_enabled: false
  # #cms_hccs_enabled: false

  # ## Core Data Model
  # core_enabled: false

  # # ## High-level Data Marts
  # readmissions_enabled: false
  # cms_chronic_conditions_enabled: false
  # tuva_chronic_conditions_enabled: false
  # ccsr_enabled: false
  # ## emergency_department_enabled: false

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  integration_tests:
    +materialized: ephemeral
#     +database: dev
#   the_tuva_project:
#     +database: dev

# seeds:
#   the_tuva_project:
#     +database: dev

