name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: tuva-snowflake

vars:

  input_database: tuva_project_demo
  input_schema: tuva_synthetic

  ## All Tuva Data Marts
  tuva_marts_enabled: true
  
  ## Individual Tuva Data Marts
  # acute_inpatient_enabled: false
  # ccsr_enabled: false
  # cms_chronic_conditions_enabled: false
  # claims_date_profiling_enabled: true
  # core_enabled: false
  # data_profiling_enabled: true
  # member_months_enabled: true
  # pmpm_enabled: false
  # readmissions_enabled: false
  # service_category_grouper_enabled: false
  # tuva_chronic_conditions_enabled: false

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  integration_tests:
    +database: dev_aaron
  the_tuva_project:
    +database: dev_aaron

seeds:
  the_tuva_project:
    +database: dev_aaron

