name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: default

vars:

  input_database: dev_ci_testing
  input_schema: claims_common
  
  tuva_database: dev_thuxuan

  ## All Data Marts
  tuva_marts_enabled: true

  ## Input Layer
  input_layer_enabled: true

  ## Claims Data Marts
  member_months_enabled: true
  service_category_grouper_enabled: true
  encounter_grouper_enabled: true
  pmpm_enabled: true
  data_profiling_enabled: true
  claims_date_profiling_enabled: true

  ## Core Data Model
  core_enabled: true

  ## High-level Data Marts
  readmissions_enabled: true
  cms_chronic_conditions_enabled: true
  tuva_chronic_conditions_enabled: true
  ccsr_enabled: true

  ## These vars are specific to the CCSR data mart
  # These vars enable the wide tables - disabling will exclude wide tables from dbt runs
  wide_condition_enabled: True
  wide_procedure_enabled: True

  # Set to "ip" for inpatient data or "op" for outpatient data (More info in the README)
  record_type: "ip"

  # CCSR Version numbers from HCUP
  dxccsr_version: "'2023.1'"
  prccsr_version: "'2023.1'"


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  integration_tests:
    +materialized: ephemeral
