default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: ./creds.json
      project: "{{ env_var('TUVA_BIGQUERY_PROJECT') }}"
      dataset: claims_input
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
